### ISSUE TITLE
Should be using arcsin instead of arctan for anglez calculation

### ISSUE THREAD

**Issue by tigretigre** [childmindresearch/wristpy#120]
https://github.com/childmindresearch/wristpy/blame/bb3eb397a7319c1630817eb883125ae3b3962001/src/wristpy/processing/metrics.py#L54

The norm, as a standin for acceleration due to gravity, is the hypotenuse of the right triangle, and the Z reading is the opposite side, so the ratio is a sine, thus to get the angle, you need to use arcsin. A pull request has been submitted for this.

**Comment by Asanto32** [comment]
Hi,

Thanks for you comment, however, it is not the magnitude of acceleration, it is only the magnitude along the x-y axis. It is the then the angle opposite (Z-axis) relative to the horizontal plane (adjacent), thus tangent is used.
