### ISSUE TITLE
Bug: The input to the `GgirSleepDetection` should be raw anglez data not the epoch1 data

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#124]
### Description

As per the definition of the the `GgirSleepDetection` class, the `self.anglez` input attribute should be the raw anglez data, however in the `orchestrator`, [it is the epoch1 data](https://github.com/childmindresearch/wristpy/blob/a41c1475785136ed5981e03b6a2b1dc6dfec82bb/src/wristpy/core/orchestrator.py#L237-L245).
```
    anglez = metrics.angle_relative_to_horizontal(calibrated_acceleration)
    if epoch_length is not None:
        enmo = computations.moving_mean(enmo, epoch_length=epoch_length)
        anglez = computations.moving_mean(anglez, epoch_length=epoch_length)


    non_wear_array = metrics.detect_nonwear(calibrated_acceleration)


    sleep_detector = analytics.GgirSleepDetection(anglez)
    sleep_windows = sleep_detector.run_sleep_detection()
```

### Steps to Reproduce

`orchestrator.run` will use the wrong anglez data for sleep detection

### Expected Results

Should be the raw anglez not downsampled anglez.

### Actual Results

Except for cases when `epoch_length is None` the orchestrator is passing the downsampled anglez data instead of raw.

### Additional Notes

@frey-perez 
@ReinderVosDeWael 
Can you verify this? Or did I miss something?

**Comment by frey-perez** [comment]
Ah, this is a good catch, I'll implement a fix, thanks Adam.
