### ISSUE TITLE
Draft Task: Handling empty sensor data from Actfast

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#27]
### Description

Currently, we raise a Value Error if the sensor data (measurement or time) is empty from Actfast. However, it is only acceleration that is a mandatory field for further analysis (enmo, angle z, sleep, physical activity metrics, etc.) This task is to built on the current architecture to handle these potentially empty Measurement fields 

### Tasks

- [ ] Task 1

### Freeform Notes

@ReinderVosDeWael Perhaps we raise the value error only for acceleration? And if a general measurement we just give a user warning??

```
def validate_accelereation(cls, v)
if v.measurements.size == 0:
raise ValueError...
```

but we try to give a warning for general empty measurements??
```
def validate_measurements_not_empty...
if v.size == 0:
warn("this field is empty")
```

**Comment by nx10** [comment]
You probably want to check len(data) == 0 first and then something like datetime[-1] - datetime[0] < minimum length to be able to process, right?

**Comment by ReinderVosDeWael** [comment]
For further discussion: an error seems to be the correct behavior, but do we want to allow for an option to ignore errors in sensors we don't strictly need?
