### ISSUE TITLE
Task: Build SleepDetection algorithm.

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/wristpy#40]
### Description

The goal of this task is to build in the main GGIR sleep detection algorithm. The class should be built to allow for the implementation of more algorithms, but those are beyond the scope of this PR.

### Tasks

- [x] Create a SleepDetectionGgir class inside wristpy/processing/analytics.py
  - [x] It contains a `run()` method taking in (probably) `enmo`, `anglez`, `nonwear` and any other necessary data. 
  - **Note**: It may be given as many private functions (prefixed by `_`) as is needed for code organization. 

### Freeform Notes

Given the complexity of the GGIR algorithm (https://github.com/wadpac/GGIR/blob/master/R/g.part4.R), the exact implementation should be considered flexible.

**Comment by Asanto32** [comment]
GGIR sleep detection implement two default algorithms for sleep detection (generally speaking, and simplified, this can be broken down as follows):
 1. The Heuristic algorithm looking at Distribution of Change in Z-Angle (HDCZA) algorithm to find the SPT-window ([reference](https://www.nature.com/articles/s41598-018-31266-z).
2. Finding SIB (sustained inactivity bouts) within the SPT-window [reference](https://doi.org/10.1371/journal.pone.0142533).

The sleep onset-wakeup times are defined by the start of the first SIB that overlaps with the SPT window and the end of the last SIB that overlaps with the SPT window.

**Comment by Asanto32** [comment]
Some questions for the next meeting (writing as I come across them):
- Will we always have access to anglez data before reaching the sleepDetection phase (seems reasonable?) 
- How/when to differentiate from non-wear (initial tests leads to non-wear appearing as sleep)
