### ISSUE TITLE
Discuss: Keep or remove GGIR calibration algorithm

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/wristpy#70]
@gkiar We've discussed adding a new calibration algorithm based on gradient descent as the GGIR algorithm seems to have odd edge cases (at least in our implementation) and it's one that we don't fully understand.

Given that we are responsible for the code we provide, even if it is based on another package, would you favor removing the GGIR calibration all-together? Verifying the correctness of our implementation would not be simple, nor could we  respond to user's issues with the algorithm with more than a casual 🤷🏻 .

**Comment by Asanto32** [comment]
Pasting Greg's response from slack for visibility:
"Keep ggir's, add warning message noting edge cases and suggesting to use our own, make our own and set it as default"
