### ISSUE TITLE
Bug: analytics._fill_short_blocks does not seem to be functioning properly in testing

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#88]
### Description

The `_fill_short_blocks` function is used to fill in short gaps in the SPT window. While the test is passing, it doesn't seem to function correctly with real data (gaps that should be filled are not, leading to multiple SPT windows that have gaps < 1hr, the default gap length)

### Steps to Reproduce

For example: Analyzing this file (1897__104846_2024-08-05 11-29-13.bin) and then looking at the SPT_windows in the generation of sleep windows, there are gaps < 1 hour (using all default settings and running `processor.process_file()` in the adhd_summer_camp_anlalysis module.

### Expected Results

There should not be any gaps < 1hour between the end of a SPT window and the start of the next.

### Actual Results

There are short gaps that aren't filled in. 

### Additional Notes

Trying to modify the unit test to see where the issue may be.

**Comment by ReinderVosDeWael** [comment]
@Asanto32 remind me about this issue during the meeting tomorrow -- we can discuss some fun strategies for dealing with these types of issues.

**Comment by Asanto32** [comment]
After discussion we will try test driven development to find the issue. 
- Write a test that fails
- Address the issue and then should be good
-
