### ISSUE TITLE
[Draft] Task: Removing non-wear time that starts before sleep Onset but ends during sleep

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#92]
### Description

How to handle the special case where sleep begins right after a period of non-wear. There is often an overlap with the ending of non-wear time and sleepOnset times. The current implementation of `remove_nonwear_from_sleep` completely removes any sleep windows that have any overlap with non-wear time. 

This might warrant a special handling case; partially remove the overlap non-wear time at the beginning (delay sleepOnset) might be one strategy?

### Tasks

- [ ] Task 1

**Comment by Asanto32** [comment]
Another special case to consider: short non-wear in the middle of sleep. For periods of sleep that are 'very calm' it can be mistaken for non-wear (see attachment). Options include: making non-wear detection less sensitive?, using longer epochs, not removing sleepWindows that have a non-wear window that starts >>> sleepWindow.onset and ends <<< sleepWindow.wakeup

<img width="641" alt="Screenshot 2024-09-12 at 10 32 59 AM" src="https://github.com/user-attachments/assets/7498ff83-f0dc-40b7-bf8e-1aa482bfcef4">
@ReinderVosDeWael @frey-perez tagging for visibility.

**Comment by ReinderVosDeWael** [comment]
Superseded by #106
